/*
 * This file is generated by jOOQ.
 */
package com.podcrash.api.db.jooq.tables.records;


import javax.annotation.Generated;

import com.podcrash.api.db.jooq.tables.Kits;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class KitsRecord extends UpdatableRecordImpl<KitsRecord> implements Record4<Long, String, Integer, String> {

    private static final long serialVersionUID = -104352297;

    /**
     * Setter for <code>public.kits.player_id</code>.
     */
    public KitsRecord setPlayerId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.kits.player_id</code>.
     */
    public Long getPlayerId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.kits.class</code>.
     */
    public KitsRecord setClass_(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.kits.class</code>.
     */
    public String getClass_() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.kits.build_id</code>.
     */
    public KitsRecord setBuildId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.kits.build_id</code>.
     */
    public Integer getBuildId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.kits.build_info</code>.
     */
    public KitsRecord setBuildInfo(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.kits.build_info</code>.
     */
    public String getBuildInfo() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record3<Long, String, Integer> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, String, Integer, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, String, Integer, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Kits.KITS.PLAYER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Kits.KITS.CLASS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Kits.KITS.BUILD_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Kits.KITS.BUILD_INFO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getPlayerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getClass_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getBuildId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getBuildInfo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getPlayerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getClass_();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getBuildId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getBuildInfo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KitsRecord value1(Long value) {
        setPlayerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KitsRecord value2(String value) {
        setClass_(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KitsRecord value3(Integer value) {
        setBuildId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KitsRecord value4(String value) {
        setBuildInfo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KitsRecord values(Long value1, String value2, Integer value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached KitsRecord
     */
    public KitsRecord() {
        super(Kits.KITS);
    }

    /**
     * Create a detached, initialised KitsRecord
     */
    public KitsRecord(Long playerId, String class_, Integer buildId, String buildInfo) {
        super(Kits.KITS);

        set(0, playerId);
        set(1, class_);
        set(2, buildId);
        set(3, buildInfo);
    }
}
