/*
 * This file is generated by jOOQ.
 */
package com.podcrash.api.db.jooq;


import javax.annotation.Generated;

import com.podcrash.api.db.jooq.tables.Descriptions;
import com.podcrash.api.db.jooq.tables.Kits;
import com.podcrash.api.db.jooq.tables.Locations;
import com.podcrash.api.db.jooq.tables.Permissions;
import com.podcrash.api.db.jooq.tables.Players;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index DESCRIPTIONS__PRIMARY_ID = Indexes0.DESCRIPTIONS__PRIMARY_ID;
    public static final Index DESCRIPTIONS__UNIQUE_KEY = Indexes0.DESCRIPTIONS__UNIQUE_KEY;
    public static final Index DESCRIPTIONS_ID = Indexes0.DESCRIPTIONS_ID;
    public static final Index KITS_PLAYER_ID_INDEX = Indexes0.KITS_PLAYER_ID_INDEX;
    public static final Index KITS_PLAYER_PRIMARY = Indexes0.KITS_PLAYER_PRIMARY;
    public static final Index LOCATIONS_PRIMARY_ID = Indexes0.LOCATIONS_PRIMARY_ID;
    public static final Index LOCATIONS_UNIQUE_NAME = Indexes0.LOCATIONS_UNIQUE_NAME;
    public static final Index PERMISSIONS_PLAYER_ID_INDEX = Indexes0.PERMISSIONS_PLAYER_ID_INDEX;
    public static final Index PERMISSIONS_UNIQUE = Indexes0.PERMISSIONS_UNIQUE;
    public static final Index PLAYERS__PRIMARY_PLAYER_ID = Indexes0.PLAYERS__PRIMARY_PLAYER_ID;
    public static final Index PLAYERS__UNIQUE_PLAYER_UUID = Indexes0.PLAYERS__UNIQUE_PLAYER_UUID;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index DESCRIPTIONS__PRIMARY_ID = Internal.createIndex("DESCRIPTIONS__primary_id", Descriptions.DESCRIPTIONS, new OrderField[] { Descriptions.DESCRIPTIONS.ID }, true);
        public static Index DESCRIPTIONS__UNIQUE_KEY = Internal.createIndex("DESCRIPTIONS__unique_key", Descriptions.DESCRIPTIONS, new OrderField[] { Descriptions.DESCRIPTIONS.KEY }, true);
        public static Index DESCRIPTIONS_ID = Internal.createIndex("DESCRIPTIONS_id", Descriptions.DESCRIPTIONS, new OrderField[] { Descriptions.DESCRIPTIONS.ID }, false);
        public static Index KITS_PLAYER_ID_INDEX = Internal.createIndex("KITS_player_id_index", Kits.KITS, new OrderField[] { Kits.KITS.PLAYER_ID }, false);
        public static Index KITS_PLAYER_PRIMARY = Internal.createIndex("KITS_player_primary", Kits.KITS, new OrderField[] { Kits.KITS.PLAYER_ID, Kits.KITS.CLASS, Kits.KITS.BUILD_ID }, true);
        public static Index LOCATIONS_PRIMARY_ID = Internal.createIndex("LOCATIONS_primary_id", Locations.LOCATIONS, new OrderField[] { Locations.LOCATIONS._ID }, true);
        public static Index LOCATIONS_UNIQUE_NAME = Internal.createIndex("LOCATIONS_unique_name", Locations.LOCATIONS, new OrderField[] { Locations.LOCATIONS.NAME }, true);
        public static Index PERMISSIONS_PLAYER_ID_INDEX = Internal.createIndex("PERMISSIONS_player_id_index", Permissions.PERMISSIONS, new OrderField[] { Permissions.PERMISSIONS.PLAYER_ID }, false);
        public static Index PERMISSIONS_UNIQUE = Internal.createIndex("PERMISSIONS_unique", Permissions.PERMISSIONS, new OrderField[] { Permissions.PERMISSIONS.PLAYER_ID, Permissions.PERMISSIONS.PERMISSION_ID }, true);
        public static Index PLAYERS__PRIMARY_PLAYER_ID = Internal.createIndex("PLAYERS__primary_player_id", Players.PLAYERS, new OrderField[] { Players.PLAYERS._ID }, true);
        public static Index PLAYERS__UNIQUE_PLAYER_UUID = Internal.createIndex("PLAYERS__unique_player_uuid", Players.PLAYERS, new OrderField[] { Players.PLAYERS.UUID }, true);
    }
}
