/*
 * This file is generated by jOOQ.
 */
package com.podcrash.api.db.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Descriptions implements Serializable {

    private static final long serialVersionUID = -1225112512;

    private final Integer id;
    private final String  key;
    private final String  value;

    public Descriptions(Descriptions value) {
        this.id = value.id;
        this.key = value.key;
        this.value = value.value;
    }

    public Descriptions(
        Integer id,
        String  key,
        String  value
    ) {
        this.id = id;
        this.key = key;
        this.value = value;
    }

    public Integer getId() {
        return this.id;
    }

    public String getKey() {
        return this.key;
    }

    public String getValue() {
        return this.value;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Descriptions (");

        sb.append(id);
        sb.append(", ").append(key);
        sb.append(", ").append(value);

        sb.append(")");
        return sb.toString();
    }
}
